/**
 * 十首 Boss 曲。结构统一：前奏 → A → B → 高潮 C（强度 ≥ 0.75 才进入）→ 间奏（强度 ≤ 0.55），
 * 循环回 A。强度分层：0.45+ 十六分镲 / 琶音，0.6+ 铜管 / 中鼓，0.75+ 合唱 / 镲片，0.9+ 主旋律八度加倍。
 * Boss 阶段推进时调用 setIntensity()，层次、速度与滤波一起抬升。
 */
import { DRUM, bars, bassRiff, chordRiff, track } from '../Compose';
import type { Composition } from '../MusicTypes';
import { FALCON, FALCON_CHORDS_A, FALCON_CHORDS_B, ORACLE, P } from './Shared';

const BOSS_INTENSITY = 0.35;
const CLIMAX = 0.75;
const CALM = 0.55;

/** 第一关 Boss「雷云」：A 小调，猎鹰动机的激进变奏 */
export const BOSS_TRACK: Composition = {
  id: 'BOSS',
  bpm: 150,
  key: 9,
  tempoRamp: 0.07,
  dynamicRange: 6,
  mix: 0.481,
  defaultIntensity: BOSS_INTENSITY,
  tracks: {
    pad: track('pad', 0.22, { params: P.warmPad, reverb: 0.3 }),
    bass: track('bass', 0.42, { params: P.bassSaw }),
    kick: track('kick', 0.82, { params: P.kickPunch }),
    snare: track('snare', 0.42, { params: P.snareTight, reverb: 0.15 }),
    hat: track('hat', 0.16, { params: P.hatClosed, pan: 0.25, maxIntensity: 0.45 }),
    hat16: track('hat', 0.14, { params: P.hatClosed, pan: 0.25, minIntensity: 0.45 }),
    arp: track('pluck', 0.15, {
      params: { ...P.pluckBright, center: 69 },
      arp: { rate: 1, mode: 'updown', octaves: 2, gate: 0.5 },
      pan: -0.3,
      minIntensity: 0.45,
    }),
    lead: track('lead', 0.28, { params: P.leadSaw, reverb: 0.2 }),
    leadHi: track('lead', 0.14, { params: P.leadSaw, pan: 0.2, minIntensity: 0.9 }),
    brass: track('brass', 0.24, { params: P.brassStab, input: 'chords', minIntensity: 0.6 }),
    choir: track('choir', 0.22, { reverb: 0.45, minIntensity: CLIMAX }),
    crash: track('cymbal', 0.16, { params: P.crash, minIntensity: 0.3 }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    chA: 'Am:16 F:16 G:16 Em:16',
    chB: 'Dm:16 F:16 Esus4:8 E:8 E:16 Dm:16 F:16 G:16 E:16',
    chC: `${FALCON_CHORDS_A} ${FALCON_CHORDS_B}`,
    bassA: bassRiff(
      ['A1', 'F1', 'G1', 'E1'],
      'R:1 R:1 O:1 R:1 R:1 R:1 O:1 R:1 R:1 R:1 O:1 R:1 R:1 R:1 O:1 R:1'
    ),
    bassB: bassRiff(
      ['D2', 'F1', 'E1', 'E1', 'D2', 'F1', 'G1', 'E1'],
      'R:1 R:1 O:1 R:1 R:1 R:1 O:1 R:1 R:1 R:1 O:1 R:1 R:1 R:1 O:1 R:1'
    ),
    bassC: bassRiff(
      ['A1', 'F1', 'C2', 'G1', 'A1', 'F1', 'G1', 'E1'],
      'R:2 R:1 R:1 O:2 R:2 R:2 R:1 R:1 O:2 R:2'
    ),
    leadA:
      'A4:2 A4:2 E5:4 C5:2 B4:2 C5:2 D5:2 | C5:4 A4:4 F5:6 E5:2 | D5:4 B4:4 G5:6 F5:2 | E5:8 G5:4 B5:4 | ' +
      'A4:2 A4:2 E5:4 C5:2 B4:2 C5:2 D5:2 | C5:4 A4:4 F5:6 E5:2 | D5:4 B4:4 G5:6 F5:2 | E5:4 B4:4 E5:8',
    leadB:
      'F5:4 A5:4 D6:8 | C6:4 A5:4 F5:8 | E5:4 A5:4 G#5:8 | B5:8 E5:8 | ' +
      'D5:4 F5:4 A5:8 | A5:4 C6:4 F5:8 | G5:4 B5:4 D6:8 | E6:8 B5:4 G#5:4',
    falcon: FALCON,
    brassA: chordRiff(['Am', 'F', 'G', 'Em'], 'R:3 R:3 R:2 -:8'),
    kick: 'X...X..xX...X.x.',
    snare: bars(DRUM.SNARE_GHOST, 7) + DRUM.SNARE_FILL,
    hat: DRUM.HAT_8,
    hat16: DRUM.HAT_16,
    crash: DRUM.CRASH_BAR + bars(DRUM.EMPTY, 3),
    crashC: DRUM.CRASH_BAR,
    riser: '-:48 C4:16',
    riser2: '-:16 C4:16',
  },
  sections: [
    { name: 'intro', bars: 2, play: { pad: 'chA', bass: 'bassA', riser: 'riser2' } },
    {
      name: 'attack',
      bars: 8,
      play: {
        pad: 'chA',
        bass: 'bassA',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        hat16: 'hat16',
        arp: 'chA',
        lead: 'leadA',
        leadHi: 'leadA^12',
        brass: 'brassA',
        crash: 'crash',
      },
    },
    {
      name: 'pressure',
      bars: 8,
      play: {
        pad: 'chB',
        bass: 'bassB',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        hat16: 'hat16',
        arp: 'chB',
        lead: 'leadB',
        leadHi: 'leadB^12',
        choir: 'chB',
        crash: 'crash',
      },
    },
    {
      name: 'falcon',
      bars: 8,
      minIntensity: CLIMAX,
      play: {
        pad: 'chC',
        bass: 'bassC',
        kick: 'kick',
        snare: 'snare',
        hat16: 'hat16',
        arp: 'chC',
        lead: 'falcon',
        leadHi: 'falcon^12',
        choir: 'chC',
        crash: 'crashC',
      },
    },
    {
      name: 'lull',
      bars: 4,
      maxIntensity: CALM,
      play: { pad: 'chA', bass: 'bassA', hat: 'hat', riser: 'riser' },
    },
  ],
  loopFrom: 1,
};

/** 第二关 Boss「沙墙」：D 弗里几亚属调式，急促手鼓与铜管齐奏的沙漠战歌 */
export const DESERT_BOSS_TRACK: Composition = {
  id: 'DESERT_BOSS',
  bpm: 140,
  key: 2,
  tempoRamp: 0.06,
  dynamicRange: 6,
  mix: 0.492,
  defaultIntensity: BOSS_INTENSITY,
  tracks: {
    drone: track('pad', 0.2, { params: { ...P.darkPad, cutoff: 900 }, reverb: 0.3 }),
    bass: track('bass', 0.44, { params: P.bassPluck }),
    riff: track('brass', 0.22, { params: P.brassStab, minIntensity: 0.6 }),
    dum: track('tom', 0.52, { params: P.dum }),
    tek: track('tom', 0.24, { params: P.tek, pan: 0.25 }),
    tek16: track('tom', 0.16, { params: P.tek, pan: -0.25, minIntensity: 0.45 }),
    kick: track('kick', 0.7, { params: P.kickPunch }),
    clap: track('clap', 0.3, { reverb: 0.2 }),
    lead: track('lead', 0.26, { params: P.zurna, reverb: 0.25 }),
    leadHi: track('lead', 0.12, { params: P.zurna, pan: 0.2, minIntensity: 0.9 }),
    choir: track('choir', 0.22, { reverb: 0.4, minIntensity: CLIMAX }),
    crash: track('cymbal', 0.16, { params: P.crash, minIntensity: 0.6 }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    drone: '[D3,A3]:32',
    choir: '[D4,A4,D5]:64 [Eb4,G4,Bb4]:64',
    bassA: 'D2:2 Eb2:2 F#2:2 G2:2 A2:4 G2:2 F#2:2 | Eb2:2 D2:2 Eb2:2 G2:2 Bb2:4 A2:2 G2:2',
    bassB:
      'G1:2 G1:2 Bb1:2 D2:2 G2:4 F#2:2 D2:2 | Eb2:2 Eb2:2 G2:2 Bb2:2 Eb3:4 D3:2 Bb2:2 | ' +
      'C2:2 C2:2 Eb2:2 G2:2 C3:4 Bb2:2 G2:2 | D2:2 Eb2:2 F#2:2 G2:2 A2:4 F#2:2 D2:2',
    leadA:
      'A5:2 G5:1 F#5:1 Eb5:2 D5:2 F#5:4 A5:4 | Bb5:4 G5:2 Eb5:2 G5:4 Bb5:2 G5:2 | ' +
      'D6:4 C6:2 Bb5:2 A5:4 F#5:4 | G5:2 F#5:2 Eb5:2 F#5:2 G5:8',
    leadB: 'G5:4 Bb5:4 D6:8 | Eb6:4 D6:2 C6:2 Bb5:8 | C6:4 G5:4 Eb5:4 G5:4 | F#5:4 A5:4 D6:8',
    dum: 'X.....X.X.......',
    tek: '.xx.x.xx.xx.x.xx',
    tek16: 'gggggggggggggggg',
    kick: DRUM.KICK_FOUR,
    clap: DRUM.SNARE_BACK,
    crash: DRUM.CRASH_BAR + bars(DRUM.EMPTY, 3),
    riser: '-:48 C4:16',
  },
  sections: [
    { name: 'intro', bars: 2, play: { drone: 'drone', dum: 'dum', bass: 'bassA' } },
    {
      name: 'charge',
      bars: 8,
      play: {
        drone: 'drone',
        bass: 'bassA',
        riff: 'bassA^24',
        dum: 'dum',
        tek: 'tek',
        tek16: 'tek16',
        kick: 'kick',
        clap: 'clap',
        lead: 'leadA',
        leadHi: 'leadA^12',
        crash: 'crash',
      },
    },
    {
      name: 'siege',
      bars: 8,
      play: {
        drone: 'drone',
        bass: 'bassB',
        riff: 'bassB^24',
        dum: 'dum',
        tek: 'tek',
        tek16: 'tek16',
        kick: 'kick',
        clap: 'clap',
        lead: 'leadB',
        leadHi: 'leadB^12',
        crash: 'crash',
      },
    },
    {
      name: 'sandstorm',
      bars: 8,
      minIntensity: CLIMAX,
      play: {
        drone: 'drone',
        choir: 'choir',
        bass: 'bassA',
        riff: 'bassA^24',
        dum: 'dum',
        tek: 'tek',
        tek16: 'tek16',
        kick: 'kick',
        clap: 'clap',
        lead: 'leadA^12',
        leadHi: 'leadA',
        crash: 'crash',
      },
    },
    {
      name: 'mirage',
      bars: 4,
      maxIntensity: CALM,
      play: { drone: 'drone', dum: 'dum', tek: 'tek', bass: 'bassA', riser: 'riser' },
    },
  ],
  loopFrom: 1,
};

/** 第三关 Boss「深渊之眼」：F 小调，半音爬行的低音、诡异钟声、断奏弦乐 */
export const OCTOPUS_BOSS_TRACK: Composition = {
  id: 'OCTOPUS_BOSS',
  bpm: 128,
  key: 5,
  tempoRamp: 0.06,
  dynamicRange: 6,
  mix: 0.55,
  defaultIntensity: BOSS_INTENSITY,
  delay: { beats: 0.75, feedback: 0.4, wet: 0.3, tone: 2200 },
  tracks: {
    pad: track('pad', 0.22, { params: P.darkPad, reverb: 0.35 }),
    bass: track('bass', 0.46, { params: P.bassSaw }),
    strings: track('pluck', 0.18, {
      params: { ...P.strings16, center: 64 },
      arp: { rate: 1, mode: 'random', octaves: 1, gate: 0.4 },
      pan: -0.25,
      minIntensity: 0.45,
    }),
    bell: track('bell', 0.16, { params: P.creepyBell, pan: 0.35, send: 0.45, reverb: 0.4 }),
    kick: track('kick', 0.8, { params: P.kickBig }),
    snare: track('snare', 0.4, { params: P.snareFat, reverb: 0.2 }),
    hat: track('hat', 0.14, { params: P.hatClosed, pan: 0.2, minIntensity: 0.45 }),
    toms: track('tom', 0.3, { params: P.taikoLow, pan: -0.2, minIntensity: 0.6 }),
    boom: track('boom', 0.44, { params: P.boom, minIntensity: 0.4 }),
    lead: track('brass', 0.3, { params: { ...P.brassLead, center: 58 }, reverb: 0.3 }),
    leadHi: track('lead', 0.14, { params: P.leadSaw, minIntensity: 0.9 }),
    choir: track('choir', 0.24, { reverb: 0.5, minIntensity: CLIMAX }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    chA: 'Fm:16 Gb:16 Fm:16 C:16',
    chB: 'Db:16 Bbm:16 Gb:16 C:16',
    bassA:
      'F1:2 F1:2 Gb1:2 F1:2 E1:2 F1:2 Ab1:2 G1:2 | Gb1:2 Gb1:2 G1:2 Gb1:2 F1:2 Gb1:2 Bb1:2 Ab1:2 | ' +
      'F1:2 F1:2 Gb1:2 F1:2 E1:2 F1:2 Ab1:2 G1:2 | C2:2 C2:2 Db2:2 C2:2 B1:2 C2:2 E2:2 C2:2',
    bassB:
      'Db2:2 Db2:2 D2:2 Db2:2 C2:2 Db2:2 F2:2 Db2:2 | Bb1:2 Bb1:2 B1:2 Bb1:2 A1:2 Bb1:2 Db2:2 Bb1:2 | ' +
      'Gb1:2 Gb1:2 G1:2 Gb1:2 F1:2 Gb1:2 Bb1:2 Gb1:2 | C2:2 C2:2 Db2:2 C2:2 B1:2 C2:2 E2:2 G2:2',
    leadA: 'F4:4 Ab4:4 C5:6 Db5:2 | Bb4:4 Db5:4 Gb5:8 | Ab4:6 G4:2 F4:8 | E4:4 G4:4 C5:8',
    leadB: 'F4:4 Ab4:4 Db5:8 | Db5:4 F5:4 Bb4:8 | Bb4:4 Db5:4 Gb5:8 | G5:4 E5:4 C5:8',
    bell: 'F5:4 B4:4 -:24',
    kick: 'X..x..X...X..x..',
    snare: bars(DRUM.SNARE_BACK, 3) + DRUM.SNARE_FILL,
    hat: DRUM.HAT_16,
    toms: '........X.x.XxXx',
    boom: DRUM.CRASH_BAR + DRUM.EMPTY,
    riser: '-:48 C4:16',
  },
  sections: [
    { name: 'intro', bars: 2, play: { pad: 'chA', bass: 'bassA', bell: 'bell' } },
    {
      name: 'tentacles',
      bars: 8,
      play: {
        pad: 'chA',
        bass: 'bassA',
        strings: 'chA',
        bell: 'bell',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        toms: 'toms',
        boom: 'boom',
        lead: 'leadA',
        leadHi: 'leadA^12',
      },
    },
    {
      name: 'abyss',
      bars: 8,
      play: {
        pad: 'chB',
        bass: 'bassB',
        strings: 'chB',
        bell: 'bell',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        toms: 'toms',
        boom: 'boom',
        lead: 'leadB',
        leadHi: 'leadB^12',
        choir: 'chB',
      },
    },
    {
      name: 'kraken',
      bars: 8,
      minIntensity: CLIMAX,
      play: {
        pad: 'chA',
        bass: 'bassA',
        strings: 'chA',
        bell: 'bell',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        toms: 'toms',
        boom: 'boom',
        lead: 'leadA^12',
        leadHi: 'leadA^12',
        choir: 'chA',
      },
    },
    {
      name: 'depths',
      bars: 4,
      maxIntensity: CALM,
      play: { pad: 'chA', bass: 'bassA', bell: 'bell', riser: 'riser' },
    },
  ],
  loopFrom: 1,
};

/** 第四关 Boss「三叉戟」：G 小调，沉重的海军进行曲：军鼓滚奏、奔马节奏与铜管号角 */
export const OCEAN_BOSS_TRACK: Composition = {
  id: 'OCEAN_BOSS',
  bpm: 120,
  key: 7,
  tempoRamp: 0.06,
  dynamicRange: 6,
  mix: 0.545,
  defaultIntensity: BOSS_INTENSITY,
  tracks: {
    pad: track('pad', 0.2, { params: P.warmPad, reverb: 0.3 }),
    bass: track('bass', 0.44, { params: P.bassSaw }),
    kick: track('kick', 0.8, { params: P.kickPunch }),
    snare: track('snare', 0.38, { params: P.snareTight, reverb: 0.15 }),
    march: track('snare', 0.24, { params: P.snareTight, pan: -0.2, minIntensity: 0.6 }),
    hat: track('hat', 0.14, { params: P.hatClosed, pan: 0.25, minIntensity: 0.45 }),
    arp: track('pluck', 0.14, {
      params: { ...P.pluckBright, center: 67 },
      arp: { rate: 1, mode: 'up', octaves: 2, gate: 0.5 },
      pan: -0.3,
      minIntensity: 0.45,
    }),
    brass: track('brass', 0.32, { params: P.brassLead, reverb: 0.25 }),
    brassHi: track('lead', 0.12, { params: P.leadSaw, pan: 0.2, minIntensity: 0.9 }),
    choir: track('choir', 0.22, { reverb: 0.45, minIntensity: CLIMAX }),
    crash: track('cymbal', 0.16, { params: P.crash }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    chA: 'Gm:16 Eb:16 Bb:16 F:16 Cm:16 Eb:16 D:16 D:16',
    chB: 'Eb:16 F:16 Gm:16 Gm:16 Eb:16 F:16 D:16 D:16',
    bassA: bassRiff(
      ['G1', 'Eb2', 'Bb1', 'F1', 'C2', 'Eb2', 'D2', 'D2'],
      'R:2 R:1 R:1 R:2 R:1 R:1 R:2 R:1 R:1 R:2 R:1 R:1'
    ),
    bassB: bassRiff(
      ['Eb2', 'F1', 'G1', 'G1', 'Eb2', 'F1', 'D2', 'D2'],
      'R:2 R:1 R:1 R:2 R:1 R:1 R:2 R:1 R:1 R:2 R:1 R:1'
    ),
    fanfare:
      'D5:2 D5:1 D5:1 G5:4 Bb5:4 A5:2 G5:2 | G5:6 Eb5:2 Bb4:8 | D5:2 D5:1 D5:1 F5:4 Bb5:6 A5:2 | ' +
      'C6:4 A5:4 F5:8 | Eb5:4 G5:4 C6:8 | Bb5:6 G5:2 Eb5:8 | F#5:4 A5:4 D6:8 | D6:4 C6:2 Bb5:2 A5:4 F#5:4',
    leadB:
      'G5:4 Bb5:4 Eb6:8 | F5:4 A5:4 C6:8 | D6:6 C6:2 Bb5:8 | G5:4 Bb5:4 D6:8 | ' +
      'Eb6:4 D6:2 C6:2 Bb5:8 | A5:4 C6:4 F6:8 | F#5:4 A5:4 D6:8 | A5:8 F#5:8',
    kick: 'X.xxX...X.xxX...',
    snare: DRUM.SNARE_BACK,
    march: 'X.xxX.x.X.xxX.xX',
    hat: DRUM.HAT_16,
    crash: DRUM.CRASH_BAR + bars(DRUM.EMPTY, 3),
    crashC: DRUM.CRASH_BAR,
    riser: '-:48 C4:16',
    riser2: '-:16 C4:16',
  },
  sections: [
    {
      name: 'intro',
      bars: 2,
      play: { pad: 'chA', bass: 'bassA', snare: 'march', riser: 'riser2' },
    },
    {
      name: 'salvo',
      bars: 8,
      play: {
        pad: 'chA',
        bass: 'bassA',
        kick: 'kick',
        snare: 'snare',
        march: 'march',
        hat: 'hat',
        arp: 'chA',
        brass: 'fanfare',
        brassHi: 'fanfare^12',
        crash: 'crash',
      },
    },
    {
      name: 'broadside',
      bars: 8,
      play: {
        pad: 'chB',
        bass: 'bassB',
        kick: 'kick',
        snare: 'snare',
        march: 'march',
        hat: 'hat',
        arp: 'chB',
        brass: 'leadB',
        brassHi: 'leadB^12',
        choir: 'chB',
        crash: 'crash',
      },
    },
    {
      name: 'trident',
      bars: 8,
      minIntensity: CLIMAX,
      play: {
        pad: 'chA',
        bass: 'bassA',
        kick: 'kick',
        snare: 'snare',
        march: 'march',
        hat: 'hat',
        arp: 'chA',
        brass: 'fanfare^12',
        brassHi: 'fanfare',
        choir: 'chA',
        crash: 'crashC',
      },
    },
    {
      name: 'swell',
      bars: 4,
      maxIntensity: CALM,
      play: { pad: 'chA', bass: 'bassA', snare: 'march', riser: 'riser' },
    },
  ],
  loopFrom: 1,
};

/** 第五关 Boss「巨像」：降 E 小调史诗，高潮段以降 E 小调完整奏响猎鹰主题 */
export const SKY_CARRIER_BOSS_TRACK: Composition = {
  id: 'SKY_CARRIER_BOSS',
  bpm: 136,
  key: 3,
  tempoRamp: 0.06,
  dynamicRange: 6,
  mix: 0.498,
  defaultIntensity: BOSS_INTENSITY,
  tracks: {
    pad: track('pad', 0.24, { params: { ...P.warmPad, voices: 3 }, reverb: 0.4 }),
    bass: track('bass', 0.42, { params: P.bassSaw }),
    kick: track('kick', 0.8, { params: P.kickBig }),
    snare: track('snare', 0.42, { params: P.snareFat, reverb: 0.25 }),
    hat: track('hat', 0.14, { params: P.hatClosed, pan: 0.25, minIntensity: 0.45 }),
    toms: track('tom', 0.3, { params: P.taikoLow, pan: -0.2, minIntensity: 0.6 }),
    arp: track('pluck', 0.15, {
      params: { ...P.pluckBright, center: 70 },
      arp: { rate: 1, mode: 'up', octaves: 2, gate: 0.5 },
      pan: -0.3,
      minIntensity: 0.45,
    }),
    lead: track('lead', 0.28, { params: P.leadSaw, reverb: 0.25 }),
    leadHi: track('lead', 0.12, { params: P.leadSaw, pan: 0.2, minIntensity: 0.9 }),
    brass: track('brass', 0.28, { params: P.brassLead, reverb: 0.3, minIntensity: 0.6 }),
    choir: track('choir', 0.24, { reverb: 0.5, minIntensity: CLIMAX }),
    crash: track('cymbal', 0.16, { params: P.crash }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    chA: 'Ebm:16 Cb:16 Gb:16 Db:16 Ebm:16 Cb:16 Db:16 Bb:16',
    chB: 'Abm:16 Cb:16 Gb:16 Db:16 Abm:16 Cb:16 Bb:16 Bb:16',
    bassA: bassRiff(
      ['Eb2', 'B1', 'Gb1', 'Db2', 'Eb2', 'B1', 'Db2', 'Bb1'],
      'R:2 R:2 O:2 R:2 R:2 R:2 O:2 R:2'
    ),
    bassB: bassRiff(
      ['Ab1', 'B1', 'Gb1', 'Db2', 'Ab1', 'B1', 'Bb1', 'Bb1'],
      'R:2 R:2 O:2 R:2 R:2 R:2 O:2 R:2'
    ),
    leadA:
      'Bb4:4 Eb5:4 Gb5:6 F5:2 | Eb5:4 Gb5:4 B5:8 | Bb5:4 Db6:4 Gb5:8 | F5:4 Ab5:4 Db6:6 C6:2 | ' +
      'Bb5:6 Gb5:2 Eb5:8 | Eb5:4 Gb5:4 B5:6 Bb5:2 | Ab5:4 F5:4 Db5:8 | D5:4 F5:4 Bb5:8',
    leadB:
      'Eb5:4 Ab5:4 Cb6:8 | Bb5:4 Gb5:4 Eb5:8 | Db5:4 Gb5:4 Bb5:8 | Ab5:6 F5:2 Db5:8 | ' +
      'Cb5:4 Eb5:4 Ab5:8 | Gb5:4 Eb5:4 Cb5:8 | D5:4 F5:4 Bb5:8 | F5:8 D5:8',
    falcon: FALCON,
    kick: 'X.....x.X.....x.',
    snare: bars(DRUM.SNARE_BACK, 7) + DRUM.SNARE_FILL,
    hat: DRUM.HAT_16,
    toms: '..........x.XxXx',
    crash: DRUM.CRASH_BAR + bars(DRUM.EMPTY, 3),
    crashC: DRUM.CRASH_BAR + DRUM.EMPTY,
    riser: '-:48 C4:16',
    riser2: '-:16 C4:16',
  },
  sections: [
    { name: 'intro', bars: 2, play: { pad: 'chA', bass: 'bassA', riser: 'riser2' } },
    {
      name: 'colossus',
      bars: 8,
      play: {
        pad: 'chA',
        bass: 'bassA',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        toms: 'toms',
        arp: 'chA',
        lead: 'leadA',
        leadHi: 'leadA^12',
        brass: 'leadA^-12',
        crash: 'crash',
      },
    },
    {
      name: 'hangar',
      bars: 8,
      play: {
        pad: 'chB',
        bass: 'bassB',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        toms: 'toms',
        arp: 'chB',
        lead: 'leadB',
        leadHi: 'leadB^12',
        choir: 'chB',
        crash: 'crash',
      },
    },
    {
      name: 'skyfall',
      bars: 8,
      minIntensity: CLIMAX,
      play: {
        pad: 'chA',
        bass: 'bassA',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        toms: 'toms',
        arp: 'chA',
        lead: 'falcon^6',
        leadHi: 'falcon^18',
        brass: 'falcon^-6',
        choir: 'chA',
        crash: 'crashC',
      },
    },
    {
      name: 'drift',
      bars: 4,
      maxIntensity: CALM,
      play: { pad: 'chA', bass: 'bassA', arp: 'chA', riser: 'riser' },
    },
  ],
  loopFrom: 1,
};

/** 第六关 Boss「熔岩巨像」：C 弗里几亚（素材按升 C 记谱、整体下移半音）半速重拍，巨鼓踏步、失真低音与锻炉合唱 */
export const MAGMA_BOSS_TRACK: Composition = {
  id: 'MAGMA_BOSS',
  transpose: -1,
  bpm: 116,
  key: 0,
  tempoRamp: 0.07,
  dynamicRange: 6,
  mix: 0.376,
  defaultIntensity: BOSS_INTENSITY,
  tracks: {
    pad: track('pad', 0.22, { params: P.darkPad, reverb: 0.35 }),
    stomp: track('boom', 0.56, { params: { ...P.boom, decay: 1.2 } }),
    taiko: track('tom', 0.5, { params: P.taikoLow }),
    taikoHi: track('tom', 0.26, { params: P.taikoHigh, pan: 0.25, minIntensity: 0.45 }),
    snare: track('snare', 0.36, { params: P.snareFat, reverb: 0.25 }),
    bass: track('bass', 0.42, { params: P.bassDist }),
    riff: track('brass', 0.22, { params: { ...P.brassStab, center: 48 }, minIntensity: 0.45 }),
    anvil: track('bell', 0.15, { params: P.anvil, pan: -0.3, reverb: 0.3, minIntensity: 0.35 }),
    lead: track('brass', 0.28, { params: P.brassLead, reverb: 0.3, minIntensity: 0.5 }),
    leadHi: track('lead', 0.12, { params: P.leadSaw, minIntensity: 0.9 }),
    choir: track('choir', 0.26, { params: { center: 58 }, reverb: 0.5, minIntensity: 0.65 }),
    crash: track('cymbal', 0.16, { params: P.crash, minIntensity: 0.5 }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    chA: 'C#m:16 D:16 C#m:16 A:8 B:8',
    chB: 'A:16 F#m:16 D:16 G#:16',
    bassA:
      'C#2:2 C#2:2 C#2:1 C#2:1 C#3:2 D2:4 C#2:4 | D2:2 D2:2 D2:1 D2:1 D3:2 E2:4 D2:4 | ' +
      'C#2:2 C#2:2 C#2:1 C#2:1 C#3:2 D2:4 C#2:4 | A1:2 A1:2 A2:2 A1:2 B1:2 B1:2 B2:2 B1:2',
    bassB:
      'A1:2 A1:2 A1:1 A1:1 A2:2 B1:4 A1:4 | F#1:2 F#1:2 F#1:1 F#1:1 F#2:2 G#1:4 F#1:4 | ' +
      'D2:2 D2:2 D2:1 D2:1 D3:2 E2:4 D2:4 | G#1:2 G#1:2 G#1:1 G#1:1 G#2:2 A1:4 G#1:4',
    leadA:
      'G#4:4 C#5:4 E5:6 D#5:2 | D5:4 F#5:4 A5:8 | G#5:6 F#5:2 E5:4 C#5:4 | C#5:4 E5:4 D#5:4 F#5:4',
    leadB: 'E5:4 A5:4 C#6:8 | C#6:4 A5:4 F#5:8 | F#5:4 A5:4 D6:8 | C6:4 D#6:4 G#5:8',
    anvil: '-:4 C#6:2 -:6 C#6:2 -:2',
    stomp: DRUM.KICK_STOMP,
    taiko: 'X..x..x.X.....x.',
    taikoHi: 'X.xxX.x.X.xxXxXx',
    snare: DRUM.SNARE_HALF,
    crash: DRUM.CRASH_BAR + bars(DRUM.EMPTY, 3),
    riser: '-:48 C4:16',
  },
  sections: [
    { name: 'intro', bars: 2, play: { pad: 'chA', stomp: 'stomp', taiko: 'taiko' } },
    {
      name: 'march',
      bars: 8,
      play: {
        pad: 'chA',
        stomp: 'stomp',
        taiko: 'taiko',
        taikoHi: 'taikoHi',
        snare: 'snare',
        bass: 'bassA',
        riff: 'bassA^12',
        anvil: 'anvil',
        lead: 'leadA',
        leadHi: 'leadA^12',
        crash: 'crash',
      },
    },
    {
      name: 'forge',
      bars: 8,
      play: {
        pad: 'chB',
        stomp: 'stomp',
        taiko: 'taiko',
        taikoHi: 'taikoHi',
        snare: 'snare',
        bass: 'bassB',
        riff: 'bassB^12',
        anvil: 'anvil',
        lead: 'leadB',
        leadHi: 'leadB^12',
        choir: 'chB',
        crash: 'crash',
      },
    },
    {
      name: 'meltdown',
      bars: 8,
      minIntensity: CLIMAX,
      play: {
        pad: 'chA',
        stomp: 'stomp',
        taiko: 'taiko',
        taikoHi: 'taikoHi',
        snare: 'snare',
        bass: 'bassA',
        riff: 'bassA^12',
        anvil: 'anvil',
        lead: 'leadA^12',
        leadHi: 'leadA^12',
        choir: 'chA',
        crash: 'crash',
      },
    },
    {
      name: 'cooling',
      bars: 4,
      maxIntensity: CALM,
      play: { pad: 'chA', stomp: 'stomp', anvil: 'anvil', riser: 'riser' },
    },
  ],
  loopFrom: 1,
};

/** 第七关 Boss「深渊利维坦」：降 B 小调，次低音长鸣、声呐、心跳到驱动的十六分低音 */
export const LEVIATHAN_BOSS_TRACK: Composition = {
  id: 'LEVIATHAN_BOSS',
  bpm: 108,
  key: 10,
  tempoRamp: 0.08,
  dynamicRange: 6,
  mix: 0.56,
  defaultIntensity: BOSS_INTENSITY,
  delay: { beats: 1.5, feedback: 0.45, wet: 0.35, tone: 1800 },
  tracks: {
    pad: track('pad', 0.24, { params: P.darkPad, reverb: 0.45 }),
    sub: track('bass', 0.42, { params: P.bassSub, maxIntensity: 0.5 }),
    pulse: track('bass', 0.38, { params: P.bassPluck, minIntensity: 0.5 }),
    sonar: track('bell', 0.18, { params: P.sonar, pan: 0.3, send: 0.5, reverb: 0.5 }),
    heart: track('kick', 0.7, { params: P.kickSoft, maxIntensity: 0.45 }),
    kick: track('kick', 0.78, { params: P.kickBig, minIntensity: 0.45 }),
    snare: track('snare', 0.34, { params: P.snareFat, reverb: 0.3, minIntensity: 0.55 }),
    toms: track('tom', 0.3, { params: P.taikoLow, pan: -0.2, minIntensity: 0.6 }),
    lead: track('lead', 0.26, {
      params: { ...P.leadSoft, attack: 0.1, vibratoHz: 4.2, vibratoCents: 24 },
      send: 0.3,
      reverb: 0.4,
    }),
    leadHi: track('lead', 0.12, { params: P.leadSaw, minIntensity: 0.9 }),
    choir: track('choir', 0.26, { params: { center: 55 }, reverb: 0.55, minIntensity: 0.7 }),
    brass: track('brass', 0.22, { params: P.brassStab, input: 'chords', minIntensity: 0.85 }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    chA: 'Bbm:16 Gb:16 Bbm:16 F:16',
    chB: 'Ebm:16 Gb:16 Db:16 F:16',
    subA: bassRiff(['Bb1', 'Gb1', 'Bb1', 'F1'], 'R:16'),
    subB: bassRiff(['Eb2', 'Gb1', 'Db2', 'F1'], 'R:16'),
    pulseA: bassRiff(
      ['Bb1', 'Gb1', 'Bb1', 'F1'],
      'R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1'
    ),
    pulseB: bassRiff(
      ['Eb2', 'Gb1', 'Db2', 'F1'],
      'R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1'
    ),
    sonar: 'F6:4 -:28',
    leadA: 'F5:8 Db5:4 Bb4:4 | Bb4:8 Db5:4 Gb5:4 | F5:6 Eb5:2 Db5:8 | C5:8 A4:8',
    leadB: 'Gb5:8 Eb5:4 Bb4:4 | Db5:8 Gb5:4 Bb5:4 | Ab5:6 F5:2 Db5:8 | C6:8 A5:8',
    brass: chordRiff(['Bbm', 'Gb', 'Bbm', 'F'], 'R:2 -:2 R:2 -:10'),
    heart: DRUM.KICK_HEART,
    kick: DRUM.KICK_FOUR,
    snare: DRUM.SNARE_BACK,
    toms: '..x...x...x.x.xx',
    riser: '-:48 C4:16',
  },
  sections: [
    { name: 'intro', bars: 2, play: { pad: 'chA', sub: 'subA', sonar: 'sonar' } },
    {
      name: 'hunt',
      bars: 8,
      play: {
        pad: 'chA',
        sub: 'subA',
        pulse: 'pulseA',
        sonar: 'sonar',
        heart: 'heart',
        kick: 'kick',
        snare: 'snare',
        toms: 'toms',
        lead: 'leadA',
        leadHi: 'leadA^12',
        brass: 'brass',
      },
    },
    {
      name: 'breach',
      bars: 8,
      play: {
        pad: 'chB',
        sub: 'subB',
        pulse: 'pulseB',
        sonar: 'sonar',
        heart: 'heart',
        kick: 'kick',
        snare: 'snare',
        toms: 'toms',
        lead: 'leadB',
        leadHi: 'leadB^12',
        choir: 'chB',
      },
    },
    {
      name: 'leviathan',
      bars: 8,
      minIntensity: CLIMAX,
      play: {
        pad: 'chA',
        pulse: 'pulseA',
        sonar: 'sonar',
        kick: 'kick',
        snare: 'snare',
        toms: 'toms',
        lead: 'leadA^12',
        leadHi: 'leadA^12',
        choir: 'chA',
        brass: 'brass',
      },
    },
    {
      name: 'silent-run',
      bars: 4,
      maxIntensity: CALM,
      play: { pad: 'chA', sub: 'subA', sonar: 'sonar', heart: 'heart', riser: 'riser' },
    },
  ],
  loopFrom: 1,
};

/** 第八关 Boss「雷霆」：F 弗里几亚金属（素材按 E 记谱、整体上移半音），双踩、颤音扫弦、闪电般的琶音与雷鸣 */
export const TEMPEST_BOSS_TRACK: Composition = {
  id: 'TEMPEST_BOSS',
  transpose: 1,
  bpm: 160,
  key: 5,
  tempoRamp: 0.05,
  dynamicRange: 6,
  mix: 0.504,
  defaultIntensity: BOSS_INTENSITY,
  tracks: {
    gtr: track('brass', 0.2, { params: P.powerChord, input: 'chords', maxIntensity: 0.6 }),
    gtr16: track('brass', 0.18, { params: P.powerChord, input: 'chords', minIntensity: 0.6 }),
    trem: track('pluck', 0.18, { params: P.tremGuitar, pan: -0.3, reverb: 0.3 }),
    bass: track('bass', 0.42, { params: P.bassSaw }),
    kick: track('kick', 0.8, { params: P.kickPunch }),
    kick2: track('kick', 0.42, { params: P.kickTight, minIntensity: 0.55 }),
    snare: track('snare', 0.44, { params: P.snareTight, reverb: 0.15 }),
    hat: track('hat', 0.16, { params: P.hatClosed, pan: 0.25 }),
    thunder: track('boom', 0.44, { params: P.thunder, reverb: 0.3, minIntensity: 0.45 }),
    crash: track('cymbal', 0.16, { params: P.crash }),
    lead: track('lead', 0.26, { params: P.guitarLead, reverb: 0.25 }),
    leadHi: track('lead', 0.12, { params: P.guitarLead, pan: 0.2, minIntensity: 0.9 }),
    shred: track('pluck', 0.14, {
      params: { ...P.pluckBright, center: 64 },
      arp: { rate: 1, mode: 'updown', octaves: 2, gate: 0.5 },
      pan: 0.3,
      minIntensity: CLIMAX,
    }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    chA: 'Epow:16 Fpow:16 Epow:16 Dpow:16',
    gtrA: chordRiff(['Epow', 'Fpow', 'Epow', 'Dpow'], 'R:2! R:2 R:2 R:2 R:2! R:2 R:2 R:2'),
    gtrB: chordRiff(['Cpow', 'Dpow', 'Bpow', 'Bpow'], 'R:2! R:2 R:2 R:2 R:2! R:2 R:2 R:2'),
    gtr16A: chordRiff(
      ['Epow', 'Fpow', 'Epow', 'Dpow'],
      'R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1'
    ),
    gtr16B: chordRiff(
      ['Cpow', 'Dpow', 'Bpow', 'Bpow'],
      'R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1 R:1! R:1 R:1 R:1'
    ),
    trem: 'E4:16 F4:16 E4:16 D4:16',
    bassA: bassRiff(['E2', 'F2', 'E2', 'D2'], 'R:2 R:1 R:1 R:2 R:1 R:1 R:2 R:1 R:1 R:2 R:1 R:1'),
    bassB: bassRiff(['C2', 'D2', 'B1', 'B1'], 'R:2 R:1 R:1 R:2 R:1 R:1 R:2 R:1 R:1 R:2 R:1 R:1'),
    leadA: 'E5:4 F5:4 G5:4 B5:4 | A5:6 C6:2 F5:8 | B5:4 G5:4 E5:8 | F#5:4 A5:4 D5:8',
    leadB: 'E5:4 G5:4 C6:8 | D6:4 A5:4 F#5:8 | D#6:4 B5:4 F#5:8 | B5:16',
    kick: DRUM.KICK_FOUR,
    kick2: DRUM.KICK_GALLOP,
    snare: bars(DRUM.SNARE_BACK, 3) + DRUM.SNARE_FILL,
    hat: DRUM.HAT_8,
    thunder: DRUM.CRASH_BAR + DRUM.EMPTY,
    crash: DRUM.CRASH_BAR + bars(DRUM.EMPTY, 3),
    riser: '-:48 C4:16',
  },
  sections: [
    { name: 'intro', bars: 2, play: { trem: 'trem', thunder: 'thunder', bass: 'bassA' } },
    {
      name: 'lightning',
      bars: 8,
      play: {
        gtr: 'gtrA',
        gtr16: 'gtr16A',
        bass: 'bassA',
        kick: 'kick',
        kick2: 'kick2',
        snare: 'snare',
        hat: 'hat',
        thunder: 'thunder',
        crash: 'crash',
        lead: 'leadA',
        leadHi: 'leadA^12',
      },
    },
    {
      name: 'coil',
      bars: 8,
      play: {
        gtr: 'gtrB',
        gtr16: 'gtr16B',
        trem: 'trem',
        bass: 'bassB',
        kick: 'kick',
        kick2: 'kick2',
        snare: 'snare',
        hat: 'hat',
        thunder: 'thunder',
        crash: 'crash',
        lead: 'leadB',
        leadHi: 'leadB^12',
      },
    },
    {
      name: 'tempest',
      bars: 8,
      minIntensity: CLIMAX,
      play: {
        gtr16: 'gtr16A',
        bass: 'bassA',
        kick: 'kick',
        kick2: 'kick2',
        snare: 'snare',
        hat: 'hat',
        thunder: 'thunder',
        crash: 'crash',
        lead: 'leadA^12',
        leadHi: 'leadA^12',
        shred: 'chA',
      },
    },
    {
      name: 'eye',
      bars: 4,
      maxIntensity: CALM,
      play: { trem: 'trem', thunder: 'thunder', bass: 'bassA', riser: 'riser' },
    },
  ],
  loopFrom: 1,
};

/** 第九关 Boss「幻影」：升 F 小调，切分的“隐身”节奏、门控和弦、全音阶幽灵动机 */
export const PHANTOM_BOSS_TRACK: Composition = {
  id: 'PHANTOM_BOSS',
  bpm: 132,
  key: 6,
  tempoRamp: 0.06,
  dynamicRange: 6,
  mix: 0.617,
  defaultIntensity: BOSS_INTENSITY,
  delay: { beats: 0.75, feedback: 0.5, wet: 0.35, tone: 2800 },
  tracks: {
    stutter: track('pad', 0.22, { params: P.gatedPad, reverb: 0.3 }),
    bells: track('bell', 0.16, { params: P.glass, pan: 0.4, send: 0.5, reverb: 0.4 }),
    bass: track('bass', 0.44, { params: P.bassPluck }),
    kick: track('kick', 0.8, { params: P.kickPunch }),
    clap: track('clap', 0.34, { reverb: 0.3 }),
    hat: track('hat', 0.16, { params: P.hatSoft, pan: -0.25 }),
    ghost: track('snare', 0.2, { params: P.snareSoft, pan: 0.2, minIntensity: 0.45 }),
    phantom: track('bell', 0.15, {
      params: P.creepyBell,
      pan: -0.4,
      send: 0.5,
      reverb: 0.4,
      minIntensity: 0.6,
    }),
    lead: track('lead', 0.26, { params: P.leadSaw, send: 0.25, reverb: 0.25 }),
    leadHi: track('lead', 0.12, { params: P.leadSaw, pan: 0.2, minIntensity: 0.9 }),
    choir: track('choir', 0.22, { reverb: 0.5, minIntensity: 0.7 }),
    brass: track('brass', 0.2, { params: P.brassStab, input: 'chords', minIntensity: 0.85 }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    chA: 'F#madd9:16 Dmaj7:16 Bm7:16 C#7sus4:8 C#7:8',
    chB: 'Dmaj7:16 E:16 C#m7:16 F#m:16',
    stutterA: chordRiff(['F#madd9', 'Dmaj7', 'Bm7', 'C#7'], 'R:3 -:1 R:2 -:2 R:1 -:1 R:3 -:3'),
    stutterB: chordRiff(['Dmaj7', 'E', 'C#m7', 'F#m'], 'R:3 -:1 R:2 -:2 R:1 -:1 R:3 -:3'),
    bells: 'C#6:2 -:2 G#5:2 -:4 F#6:2 -:4',
    bassA: bassRiff(['F#1', 'D2', 'B1', 'C#2'], 'R:3 R:3 O:2 -:2 R:2 F:2 R:2'),
    bassB: bassRiff(['D2', 'E2', 'C#2', 'F#1'], 'R:3 R:3 O:2 -:2 R:2 F:2 R:2'),
    phantom: 'F#5:2 G#5:2 A#5:2 C6:2 D6:4 -:4 | -:16',
    leadA: 'C#5:4 G#5:4 F#5:4 A5:4 | F#5:6 E5:2 C#5:8 | D5:4 F#5:4 A5:6 B5:2 | F#5:4 G#5:4 F5:8',
    leadB: 'A5:4 F#5:4 C#6:8 | B5:4 G#5:4 E5:8 | E5:4 G#5:4 B5:6 C#6:2 | A5:8 F#5:8',
    brass: chordRiff(['F#m', 'D', 'Bm', 'C#'], 'R:2 -:6 R:2 -:6'),
    kick: 'X.....x...x.....',
    clap: '............X...',
    hat: 'x.xx..x.x..x.x..',
    ghost: '..g..g...g..g..g',
    riser: '-:48 C4:16',
  },
  sections: [
    { name: 'intro', bars: 2, play: { stutter: 'stutterA', bells: 'bells' } },
    {
      name: 'cloak',
      bars: 8,
      play: {
        stutter: 'stutterA',
        bells: 'bells',
        bass: 'bassA',
        kick: 'kick',
        clap: 'clap',
        hat: 'hat',
        ghost: 'ghost',
        phantom: 'phantom',
        lead: 'leadA',
        leadHi: 'leadA^12',
        brass: 'brass',
      },
    },
    {
      name: 'decoys',
      bars: 8,
      play: {
        stutter: 'stutterB',
        bells: 'bells',
        bass: 'bassB',
        kick: 'kick',
        clap: 'clap',
        hat: 'hat',
        ghost: 'ghost',
        phantom: 'phantom',
        lead: 'leadB',
        leadHi: 'leadB^12',
        choir: 'chB',
      },
    },
    {
      name: 'overdrive',
      bars: 8,
      minIntensity: CLIMAX,
      play: {
        stutter: 'stutterA',
        bells: 'bells',
        bass: 'bassA',
        kick: 'kick',
        clap: 'clap',
        hat: 'hat',
        ghost: 'ghost',
        phantom: 'phantom',
        lead: 'leadA^12',
        leadHi: 'leadA^12',
        choir: 'chA',
        brass: 'brass',
      },
    },
    {
      name: 'vanish',
      bars: 4,
      maxIntensity: CALM,
      play: { stutter: 'stutterA', bells: 'bells', phantom: 'phantom', riser: 'riser' },
    },
  ],
  loopFrom: 1,
};

/**
 * 最终 Boss「神谕主宰」：C 小调。按强度依次展开：苏醒（≤0.55）→ 护盾 → 核心（≥0.7）
 * → 终焉之光（≥0.88，铜管以 C 小调奏响完整猎鹰主题，与神谕动机对抗）。
 */
export const ORACLE_BOSS_TRACK: Composition = {
  id: 'ORACLE_BOSS',
  bpm: 132,
  key: 0,
  tempoRamp: 0.06,
  dynamicRange: 6,
  mix: 0.449,
  defaultIntensity: 0.6,
  delay: { beats: 0.75, feedback: 0.4, wet: 0.3, tone: 2400 },
  tracks: {
    choir: track('choir', 0.28, { params: { center: 60, width: 0.7 }, reverb: 0.55 }),
    organ: track('pad', 0.18, { params: P.organ, reverb: 0.35 }),
    oracle: track('bell', 0.18, { params: P.creepyBell, pan: 0.3, send: 0.45, reverb: 0.45 }),
    sub: track('bass', 0.4, { params: P.bassSub }),
    bass: track('bass', 0.4, { params: P.bassSaw }),
    heart: track('kick', 0.7, { params: P.kickBig }),
    kick: track('kick', 0.8, { params: P.kickPunch }),
    kick2: track('kick', 0.4, { params: P.kickTight, minIntensity: 0.88 }),
    snare: track('snare', 0.42, { params: P.snareFat, reverb: 0.25 }),
    hat: track('hat', 0.14, { params: P.hatClosed, pan: 0.25, minIntensity: 0.45 }),
    toms: track('tom', 0.3, { params: P.taikoLow, pan: -0.2, minIntensity: 0.6 }),
    boom: track('boom', 0.46, { params: P.boom }),
    arp: track('pluck', 0.14, {
      params: { ...P.pluckBright, center: 67 },
      arp: { rate: 1, mode: 'updown', octaves: 2, gate: 0.5 },
      pan: -0.3,
      minIntensity: 0.5,
    }),
    lead: track('lead', 0.27, { params: { ...P.leadSaw, wave2: 'square' }, reverb: 0.25 }),
    leadHi: track('lead', 0.12, { params: P.leadSaw, pan: 0.2, minIntensity: 0.95 }),
    brass: track('brass', 0.3, { params: P.brassLead, reverb: 0.3, minIntensity: 0.7 }),
    stabs: track('brass', 0.2, { params: P.brassStab, input: 'chords', minIntensity: 0.75 }),
    crash: track('cymbal', 0.16, { params: P.crash }),
    riser: track('riser', 0.2, { input: 'notes' }),
  },
  patterns: {
    chAwake: 'Cm:16 Ab:16 Db:16 G:16',
    chShield: 'Cm:16 Ab:16 Fm:16 G:16',
    chCore: 'Ab:16 Bb:16 Cm:16 Cm:16 Ab:16 Bb:16 G:16 G:16',
    chLight: 'Cm:16 Ab:16 Eb:16 Bb:16 Cm:16 Ab:16 Bb:16 G:16',
    subAwake: bassRiff(['C2', 'Ab1', 'Db2', 'G1'], 'R:16'),
    bassShield: bassRiff(
      ['C2', 'Ab1', 'F1', 'G1'],
      'R:1! R:1 O:1 R:1 R:1 R:1 O:1 R:1 R:1! R:1 O:1 R:1 R:1 R:1 O:1 R:1'
    ),
    bassCore: bassRiff(
      ['Ab1', 'Bb1', 'C2', 'C2', 'Ab1', 'Bb1', 'G1', 'G1'],
      'R:1! R:1 O:1 R:1 R:1 R:1 O:1 R:1 R:1! R:1 O:1 R:1 R:1 R:1 O:1 R:1'
    ),
    bassLight: bassRiff(
      ['C2', 'Ab1', 'Eb2', 'Bb1', 'C2', 'Ab1', 'Bb1', 'G1'],
      'R:2 R:1 R:1 O:2 R:2 R:2 R:1 R:1 O:2 R:2'
    ),
    oracle: ORACLE,
    leadShield:
      'C5:4 F#5:4 G5:4 Eb5:4 | Ab4:4 C5:4 Eb5:8 | F5:4 Ab5:4 C6:4 B5:2 Ab5:2 | G5:8 D5:4 B4:4',
    leadCore:
      'C6:4 Ab5:4 Eb5:8 | D6:4 Bb5:4 F5:8 | Eb6:4 C6:4 G5:8 | G5:4 Bb5:4 C6:8 | ' +
      'Ab5:4 C6:4 Eb6:8 | F6:4 D6:4 Bb5:8 | B5:4 D6:4 G6:8 | G6:8 F6:4 D6:4',
    falcon: FALCON,
    stabs: chordRiff(['Ab', 'Bb', 'Cm', 'Cm', 'Ab', 'Bb', 'G', 'G'], 'R:3 R:3 R:2 -:8'),
    heart: 'X.......x.......',
    kick: DRUM.KICK_FOUR,
    kick2: DRUM.KICK_GALLOP,
    snare: bars(DRUM.SNARE_BACK, 7) + DRUM.SNARE_ROLL,
    hat: DRUM.HAT_16,
    toms: '........x.x.XxXx',
    boom: DRUM.CRASH_BAR + DRUM.EMPTY,
    crash: DRUM.CRASH_BAR + bars(DRUM.EMPTY, 3),
    crashC: DRUM.CRASH_BAR,
    riser: '-:112 C4:16',
  },
  sections: [
    { name: 'intro', bars: 2, play: { choir: 'chAwake', oracle: 'oracle', boom: 'boom' } },
    {
      name: 'awakening',
      bars: 8,
      maxIntensity: CALM,
      play: {
        choir: 'chAwake',
        organ: 'chAwake',
        oracle: 'oracle',
        sub: 'subAwake',
        heart: 'heart',
        boom: 'boom',
        riser: 'riser',
      },
    },
    {
      name: 'shield',
      bars: 8,
      play: {
        choir: 'chShield',
        organ: 'chShield',
        oracle: 'oracle',
        bass: 'bassShield',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        toms: 'toms',
        boom: 'boom',
        arp: 'chShield',
        lead: 'leadShield',
        crash: 'crash',
      },
    },
    {
      name: 'core',
      bars: 8,
      minIntensity: 0.7,
      play: {
        choir: 'chCore',
        organ: 'chCore',
        bass: 'bassCore',
        kick: 'kick',
        snare: 'snare',
        hat: 'hat',
        toms: 'toms',
        boom: 'boom',
        arp: 'chCore',
        lead: 'leadCore',
        leadHi: 'leadCore^12',
        stabs: 'stabs',
        crash: 'crash',
      },
    },
    {
      name: 'last-light',
      bars: 8,
      minIntensity: 0.88,
      play: {
        choir: 'chLight',
        organ: 'chLight',
        oracle: 'oracle',
        bass: 'bassLight',
        kick: 'kick',
        kick2: 'kick2',
        snare: 'snare',
        hat: 'hat',
        toms: 'toms',
        boom: 'boom',
        arp: 'chLight',
        brass: 'falcon^3',
        lead: 'falcon^15',
        leadHi: 'falcon^15',
        crash: 'crashC',
      },
    },
  ],
  loopFrom: 1,
};
